### ISSUE TITLE
Разработка стартера cra-login-formik-ts-starter

### ISSUE THREAD

**Issue by AlexanderLapygin** [Jepria/jfront#40]
# Разработка стартера *cra-login-formik-ts-starter*

Общая схема разработки [здесь](https://raw.githubusercontent.com/Jepria/doc/master/jfront/images/jfront-plan.svg?sanitize=true)

## Необходимые свойства

- basic-auth
- client
- create-react-app
- express
- formik
- ie11
- integration-test
- login
- jest
- rest
- starter
- typescript
- ui-test

## Главная цель

Создание стартера на основе *Create React App*,  на *TypeScript* с поддержкой *IE11*, взаимодействующего с сервером по *REST API*, реализующего аутентификацию с использованием Login-формы, сделанной с помощью библиотеки *Formik*.

## Целевой репозиторий
Создаётся fork-ом из оригинального по готовности

## Взаимодействие

Первоначальная разработка ведётся в оригинальном репозитории разработчика. После получения результата приёмщик выполняет fork оригинального репозитория в целевой.  Если возникает необходимость в доработках, их результаты досылаются Pull Request-ами из оригинального репозитория в целевой.

**Comment by AlexanderLapygin** [comment]
Замечания:
- В старты скриптов вставить *run*, например, вместо *npm start:server* нужно *npm **run** start:server*
- Думаю, раздел Readme *Application scripts* лучше убрать, тем более, что там ошибка.
- Заменить использование *Emotion* на *Styled Components* - я упоминал в [Новости с JFront-а (выпуск 1)](http://vsmlapprfid1/newsletter/jepria/18-03-2020/jfront-news-1/index.html), что мы ориентируемся на *Styled Components*.
- Привести перечень *Readme.Feature Tags* в соответствие с issue и добавить туда *styled-components*.
- Поскольку в свойствах значится *jest*:
  - добавить интеграционные тесты для REST API (лучше - на основе тестов [предка](https://github.com/softspiders/basicauth-rest-client-jest-starter))
  - Сделать несколько UI-тестов для логин-формы. Это важный момент. Для этого нужно войти в тему, не слишком торопясь. Посмотреть best practice, их сейчас много разных. Выбери пока на своё усмотрение.
- Заменить *SignUp* на *SignIn*

А так вообще пока всё очень здорово, я бы даже сказал, многообещающе)

**Comment by AlexanderLapygin** [comment]
В App.tsx:
~~~
    <div>
      <LoginForm />
    </div>
~~~

Зачем нужен *div* ?

**Comment by AlexanderLapygin** [comment]
При запуске в IE 11 и вводе неверных значений логин/пароль выдаётся сообщение "Авторизация успешна"

**Comment by Kazeev** [comment]
Хм... Я и не заметил. Приеду, поправлю  пятница, 20 марта 2020г., 12:55 +03:00 от Alexander Lapygin  notifications@github.com :

**Comment by AlexanderLapygin** [comment]
Миш, поправь, пожалуйста, картинку, чтоб форма по центру была
И SignUp всё-таки замени на SignIn)
