### ISSUE TITLE
Разработка стартера cra-ts-starter

### ISSUE THREAD

**Issue by AlexanderLapygin** [Jepria/jfront#41]
# Разработка стартера *cra-ts-starter*

Общая схема разработки [здесь](https://raw.githubusercontent.com/Jepria/doc/master/jfront/images/jfront-plan.svg?sanitize=true)

## Необходимые свойства
- create-react-app
- starter
- template
- typescript

## Главная цель
Создание стартера на основе [Create React App](https://create-react-app.dev/), реализованного на TypeScript.

## Целевой репозиторий
[cra-ts-starter](https://github.com/softspiders/cra-ts-starter)

**Comment by remitot** [comment]
Завершено
